### ISSUE TITLE
Error handling / reconnection logic needed

### ISSUE THREAD

**Issue by qozle** [qozle/wall-of-cats#5]
Sometimes connections die.  It's just part of life- it happens to every connection. 

```

Error: Connection lost: The server closed the connection.
    at Protocol.end (/var/www/html/01014.org/public_html/srv/node_modules/mysql/lib/protocol/Protocol.js:112:13)
    at Socket.<anonymous> (/var/www/html/01014.org/public_html/srv/node_modules/mysql/lib/Connection.js:94:28)
    at Socket.<anonymous> (/var/www/html/01014.org/public_html/srv/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  fatal: true,
  code: 'PROTOCOL_CONNECTION_LOST'
}
``` 

It looks like, after a number of hours, the server stopped getting keep-alive signals and data from the twitter server.  A little while after that, the MYSQL server lost it's connection somehow and that was that.  The server was still running (it was still cleaning out the DB every 3m like it should).

It -should- be catching timeouts from the twitter server.  And it didn't seem to.  So I don't know what happened there.  It should also be catching errors sent from the twitter server.  So.  Not sure what's going on there yet. 

This should just need some reconnection logic added in, so that if a disconnection happens with either the twitter server or the MYSQL server, it'll remake the connection.  This shouldn't be too hard because it's using a connection pool.

**Comment by qozle** [comment]
fixed by 1a1ccec9e76b87464e6b1e2322e258b21705b7d5
