### ISSUE TITLE
MYSQL connection issue

### ISSUE THREAD

**Issue by qozle** [qozle/wall-of-cats#7]
Not sure why, but if the server is left running long enough, it will throw this error:
```There was an error with the get request to the twitter server:

Error: connect ECONNREFUSED 23.1.99.237:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '23.1.99.237',
  port: 443
}
```

which will eventually turn into: 

```
There was an error with the get request to the twitter server:

Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:609:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1547:19)
    at Object.onceWrapper (events.js:420:28)
    at TLSSocket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ECONNRESET',
  path: null,
  host: 'pbs.twimg.com',
  port: 443,
  localAddress: undefined
}
```

It seems it fixes itself though- I've seen this happen a few times.  The connection to the twitter server stays open and the server continues to receive data, but just won't put it in the DB.  I think eventually the connection from the pool is timed out and a new one is created?  

Still, there should be some kind of reconnection logic on MYSQL errors.

**Comment by qozle** [comment]
1e9cbe5d882bcd1fa122c1b930e087886b436343 fixes this.

Added in logic to reconnect on connection issues.
